services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_NAME}" ]
      interval: 1s
      timeout: 5s
      retries: 3
    restart: always
    volumes:
      - ./prod_postgres_data/:/var/lib/postgresql/data
    networks:
      - my_network

  backend:
    build:
      dockerfile: Dockerfile-fastapi
    stop_signal: SIGKILL
    env_file:
      - .env
    container_name: fastapi-view
    ports:
      - "8000:8000"
    command: ["/app/docker-entrypoint.sh"]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my_network


  http_client:
    build:
      dockerfile: Dockerfile-client
    stop_signal: SIGKILL
    env_file:
      - .env
    container_name: http_client
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my_network

volumes:
  prod_postgres_data:

networks:
  my_network:
    driver: bridge