FROM python:3.12-slim

RUN mkdir /http_client

WORKDIR /http_client

COPY pyproject.toml poetry.lock ./

RUN pip install poetry && poetry config virtualenvs.create false && poetry install --only http_client

COPY . .

CMD ["python", "-m", "src.http_client.http_client"]

# docker build -f Dockerfile-fastapi-client -t http_client .